version: "3.8"

services:
  api-prod:
    container_name: chesswar-api-prod
    image: chesswar-api-prod
    build:
      context: /projects/chesswar/prod/repo
      dockerfile: Dockerfile-api
    restart: unless-stopped

    networks:
      - chesswar-prod
      - chesswar-internal-prod

    labels:
      traefik.enable: true
      traefik.docker.network: chesswar-prod
      traefik.http.routers.chesswarApiProd.rule: Host(`api.chesswar.io`)
      traefik.http.routers.chesswarApiProd.entrypoints: websecure

  web-prod:
    container_name: chesswar-web-prod
    image: chesswar-web-prod
    build:
      context: /projects/chesswar/prod/repo
      dockerfile: Dockerfile-web
    restart: unless-stopped

    networks:
      - chesswar-prod

    labels:
      traefik.enable: true
      traefik.docker.network: chesswar-prod
      traefik.http.routers.chesswarWebProd.rule: Host(`chesswar.io`)
      traefik.http.routers.chesswarWebProd.entrypoints: websecure

networks:
  chesswar-prod:
    external: true
  chesswar-internal-prod:
    external: false
