name: chesswar-prod

services:
  api:
    container_name: chesswar-prod-api
    build:
      context: &repo_path /projects/chesswar/prod/repo
      dockerfile: Dockerfile-api
    restart: unless-stopped

    networks:
      - chesswar-prod
      - chesswar-prod-internal

    labels:
      traefik.enable: true
      traefik.docker.network: chesswar-prod
      traefik.http.routers.chesswarApiProd.rule: Host(`api.chesswar.io`)
      traefik.http.routers.chesswarApiProd.entrypoints: websecure

  web:
    container_name: chesswar-prod-web
    build:
      context: *repo_path
      dockerfile: Dockerfile-web
    restart: unless-stopped

    networks:
      - chesswar-prod

    labels:
      traefik.enable: true
      traefik.docker.network: chesswar-prod
      traefik.http.routers.chesswarWebProd.rule: Host(`chesswar.io`)
      traefik.http.routers.chesswarWebProd.entrypoints: websecure

networks:
  chesswar-prod:
    external: true
  chesswar-prod-internal:
    external: false
