name: chesswar-dev

services:
  api:
    container_name: chesswar-dev-api
    build:
      context: /projects/chesswar/dev/repo
      dockerfile: Dockerfile-api
    restart: unless-stopped

    networks:
      - chesswar-dev
      - chesswar-dev-internal

    labels:
      traefik.enable: true
      traefik.docker.network: chesswar-dev
      traefik.http.routers.chesswarApiDev.rule: Host(`api.chesswar.dev`)
      traefik.http.routers.chesswarApiDev.entrypoints: websecure

  web:
    container_name: chesswar-dev-web
    build:
      context: /projects/chesswar/dev/repo
      dockerfile: Dockerfile-web
    restart: unless-stopped

    networks:
      - chesswar-dev

    labels:
      traefik.enable: true
      traefik.docker.network: chesswar-dev
      traefik.http.routers.chesswarWebDev.rule: Host(`chesswar.dev`)
      traefik.http.routers.chesswarWebDev.entrypoints: websecure

networks:
  chesswar-dev:
    external: true
  chesswar-dev-internal:
    external: false
