version: "3.8"

services:
  traefik:
    container_name: traefik
    image: traefik:2.5
    restart: always

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /projects/configs/traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - /projects/configs/traefik/dynamic/:/traefik/dynamic/
      - /projects/secrets/traefik/:/traefik/secrets/

    ports:
      - 80:80
      - 443:443

    networks:
      - clerk
      - odyssey

networks:
  clerk:
    external: true
  odyssey:
    external: true
